db:
  image: mongo
  command: mongod
backend:
  build: .
  dockerfile: ./backend_node/Dockerfile
  volumes:
    - .:/backend_node
  ports:
    - "8000:8000"
    - "3000:3000"
    - "27017:27017"
  links:
    - db
frontend:
  build: .
  dockerfile: ./frontend/Dockerfile
  volumes:
    - .:/frontend
  ports:
    - "80:80"
